import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'org.jetbrains.kotlin.jvm' version "${kotlin_version}"
	id 'org.jetbrains.kotlin.plugin.serialization' version "${kotlin_version}"
}

def versionProperties = new Properties()
file("versions/${project.mc}.properties").withInputStream { versionProperties.load(it) }
versionProperties.each { key, value -> project.ext.set(key, value) }

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

sourceSets.main.kotlin.srcDir("src/compat/${project.compat}/kotlin")

repositories {
	maven { url = "https://maven.notenoughupdates.org/releases/" }
	maven { url = "https://repo.hypixel.net/repository/Hypixel/" }
	maven {
		url = "https://api.modrinth.com/maven"
		content {
			includeGroup "maven.modrinth"
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "net.fabricmc:fabric-language-kotlin:${project.fabric_kotlin_version}"

	implementation "org.notenoughupdates.moulconfig:${project.moulconfig_artifact}:${project.moulconfig_version}"
	include "org.notenoughupdates.moulconfig:${project.moulconfig_artifact}:${project.moulconfig_version}"

	compileOnly "maven.modrinth:modmenu:${project.modmenu_version}"
	localRuntime "maven.modrinth:modmenu:${project.modmenu_version}"

	compileOnly "net.hypixel:mod-api:${project.hypixel_modapi_version}"
	localRuntime "maven.modrinth:hypixel-mod-api:${project.hypixel_modapi_fabric_version}"

	testImplementation platform("org.junit:junit-bom:${project.junit_version}")
	testImplementation "org.junit.jupiter:junit-jupiter"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

test {
	useJUnitPlatform()
}

loom {
	runs {
		removeIf { it.name != "client" }
	}
}

processResources {
	inputs.property "version", project.version
	inputs.property "minecraft_range", project.minecraft_range

	filesMatching("fabric.mod.json") {
		expand "version": project.version, "minecraft_range": project.minecraft_range
	}
}

tasks.withType(Jar).configureEach {
	archiveVersion = "v${project.mod_version}-${project.mc}"
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 25
}

kotlin {
	compilerOptions {
		jvmTarget = JvmTarget.JVM_25
	}
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	from("LICENSE") {
		rename { "${it}_${base.archivesName.get()}" }
	}
}

apply from: "gradle/release.gradle"
